# ====================================
# ChestShop Plugin Configuration
# ====================================

# Configuration version (DO NOT CHANGE MANUALLY!)
config-version: 3

# General Settings
general:
  # Maximum number of shops per player (0 = unlimited)
  max-shops-per-player: 10
  
  # Allowed worlds for ChestShops (empty = all worlds)
  allowed-worlds: []
  
  # Maintenance mode (disables all shop interactions)
  maintenance-mode: false

# Shop Settings
shop:
  # Price limits
  price-limits:
    min-buy-price: 0.01
    max-buy-price: 1000000.0
    min-sell-price: 0.01
    max-sell-price: 1000000.0
  
  # Shop creation
  creation:
    # Cost for creating a shop
    creation-cost: 100.0
    
    # Allowed items for shops (empty = all items allowed)
    allowed-items: []
    
    # Banned items for shops
    banned-items:
      - "BEDROCK"
      - "COMMAND_BLOCK"
      - "STRUCTURE_BLOCK"
      - "BARRIER"
      - "END_PORTAL_FRAME"
  
  # Shop behavior
  behavior:
    # Shop owner can access their own shop for free
    owner-free-access: true

# Sign Settings
signs:
  # Shop sign format
  format:
    line1: "&9[ChestShop]"
    line2: "&b%owner%"
    line3: "&a%amount% %item%"
    line4: "&eB: %buy% S: %sell%"
  
  # Sign colors based on shop status
  colors:
    active: "&a"
    inactive: "&c"
    out-of-stock: "&6"
    out-of-space: "&6"

# Hologram Settings
holograms:
  # Enable holographic displays above shops
  enabled: true
  
  # Show floating item above chest
  show-item: true
  
  # Show text information
  show-text: true
  
  # Show price information
  show-prices: true
  
  # Text format for shop info hologram
  text-format: "&6[ChestShop] &b%owner%"
  
  # Price format for price hologram
  price-format: "&aBuy: %buy% &cSell: %sell%"
  
  # Trading shop text format (only used when item trading is enabled)
  trading-text-format: "&9[ItemShop] &b%owner%"
  
  # Trading shop price format (shows item exchange ratio)
  trading-price-format: "&e%buy_amount%x %buy_item% &6-> &a%sell_amount%x %sell_item%"

# Protection Settings
protection:
  # Enable shop protection
  enabled: true
  
  # Only shop owner can break chest and sign
  only-owner-break: true
  
  # Hopper protection (prevents item extraction via hoppers)
  hopper-protection: true
  
  # Shop owners can access their shop chests
  allow-owner-inventory-access: true
  
  # Prevent dangerous blocks near shops
  protect-nearby-blocks: true

# Logging Settings
logging:
  # Log all transactions
  log-transactions: true
  
  # Log admin actions
  log-admin-actions: true

# Notification Settings
notifications:
  # Notifications for low stock
  low-stock:
    enabled: true
    # Threshold for low stock warning
    threshold: 5
    
  # Notifications when shop is full
  full-shop:
    enabled: true
    
  # Login notifications for shop owners
  login-notifications:
    enabled: true
    # Show summary of shop status on login
    show-summary: true

# Search Settings
search:
  # Maximum results to show per search
  max-results: 10

# ====================================
# ITEM TRADING FEATURE (OPTIONAL)
# ====================================
# This feature allows players to create shops that trade items for items
# instead of using money. Set 'enabled' to false to completely disable.
item-trading:
  # Master switch - set to false to completely disable item trading
  enabled: false
  
  # Shop creation settings
  creation:
    # Allow creating pure item trading shops (no money involved)
    allow-item-only-shops: true
    
    # Cost multiplier for creating item trading shops (relative to normal shop cost)
    creation-cost-multiplier: 1.5
    
    # Require exact item match (including NBT, enchantments, durability)
    require-exact-match: false
    
    # Allow damaged items in trading
    allow-damaged-items: true
    
    # Allow enchanted items in trading
    allow-enchanted-items: true
    
    # Allow items with custom names/lore
    allow-custom-items: true
    
    # Show command help in /cs help (when enabled)
    show-in-help: true
  
  # Trading behavior settings
  behavior:
    # Show detailed item preview in chat before trading
    show-item-preview: true
    
    # Require shift+click to confirm item trades (adds safety)
    require-shift-click: true
    
    # Allow partial item trades (if player has less than required amount)
    allow-partial-trades: false
    
    # Trading cooldown per player in seconds (0 = disabled)
    trading-cooldown: 5
    
    # Maximum distance for item trading in blocks (0 = no limit)
    max-trading-distance: 10
    
    # Auto-convert compatible items (e.g., logs to planks)
    auto-convert-items: false
    
    # Log item trades to console/file
    log-item-trades: true
  
  # Item validation settings
  validation:
    # Check item durability when trading
    check-durability: false
    
    # Minimum durability percentage required for trading
    min-durability-percent: 50
    
    # Check enchantment levels exactly
    check-enchantments: false
    
    # Allow higher enchantment levels than required
    allow-higher-enchantments: true
    
    # Check custom model data
    check-custom-model-data: false
    
    # Check item display names
    check-display-names: false
  
  # Trading restrictions
  restrictions:
    # Items specifically banned from item trading (in addition to general shop bans)
    banned-trading-items:
      - "NETHERITE_SCRAP"
      - "ANCIENT_DEBRIS"
      - "DRAGON_EGG"
    
    # Maximum value difference between traded items (0 = disabled, requires economy plugin)
    max-value-difference: 0
    
    # Block trading between different worlds
    same-world-only: false
    
    # Require both items to be in same category (food, tools, etc.)
    same-category-only: false
    
    # Maximum trades per player per day (0 = unlimited)
    max-trades-per-day: 0
  
  # Notification settings
  notifications:
    # Notify shop owner when item trade occurs
    notify-owner: true
    
    # Notify player when trade completes
    notify-trader: true
  
  # Advanced settings
  advanced:
    # Clean up expired trade confirmations (minutes)
    cleanup-expired-trades: 5
