# Modern Paper Plugin Configuration
name: ChestShop
version: '${project.version}'
main: de.flori.chestShop.ChestShopPlugin
bootstrapper: de.flori.chestShop.ChestShopBootstrap
description: A user-friendly ChestShop plugin for Paper 1.21.5 with advanced features
authors:
  - Flori
contributors: []
website: https://github.com/your-username/chestshop

# Paper-specific settings
api-version: '1.21'
folia-supported: false
load: STARTUP
has-open-classloader: false

# Dependencies
dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true


# Permissions
permissions:
  # Basic permissions
  chestshop.*:
    description: Grants access to all ChestShop commands
    children:
      - chestshop.use
      - chestshop.create
      - chestshop.remove
      - chestshop.info
      - chestshop.refill
      - chestshop.toggle
      - chestshop.price
      - chestshop.search
      - chestshop.stats
      - chestshop.list
      - chestshop.list.others
      - chestshop.trading.*
      - chestshop.admin.*
    default: OP

  # User permissions
  chestshop.use:
    description: Basic permission to use ChestShop commands
    default: TRUE

  chestshop.create:
    description: Allows creating shops
    default: TRUE

  chestshop.remove:
    description: Allows removing own shops
    default: TRUE

  chestshop.info:
    description: Allows viewing shop information
    default: TRUE

  chestshop.refill:
    description: Allows refilling own shops
    default: TRUE

  chestshop.toggle:
    description: Allows toggling own shops on/off
    default: TRUE

  chestshop.price:
    description: Allows updating shop prices
    default: TRUE

  chestshop.search:
    description: Allows searching for shops
    default: TRUE

  chestshop.stats:
    description: Allows viewing own shop statistics
    default: TRUE

  chestshop.list:
    description: Allows listing own shops
    default: TRUE

  chestshop.list.others:
    description: Allows listing other players' shops
    default: OP

  # Shop creation permissions
  chestshop.create.unlimited:
    description: Bypass shop creation limits
    default: OP

  chestshop.create.free:
    description: Create shops without cost
    default: OP

  chestshop.create.banned-items:
    description: Create shops with banned items
    default: OP

  chestshop.create.anywhere:
    description: Create shops in any world
    default: OP

  # Shop interaction permissions
  chestshop.buy:
    description: Allows buying from shops
    default: TRUE

  chestshop.sell:
    description: Allows selling to shops
    default: TRUE

  chestshop.buy.free:
    description: Buy items without cost
    default: FALSE

  chestshop.sell.overprice:
    description: Bypass sell price limits
    default: FALSE

  # Protection bypass permissions
  chestshop.protection.bypass:
    description: Bypass all shop protections
    default: OP

  chestshop.protection.access-all:
    description: Access any shop chest
    default: OP

  chestshop.protection.break-any:
    description: Break any shop blocks
    default: OP

  chestshop.protection.place-anywhere:
    description: Place blocks near any shop
    default: OP

  # Notification permissions
  chestshop.notifications.receive:
    description: Receive shop notifications
    default: TRUE

  chestshop.notifications.others:
    description: Receive notifications about other players' shops
    default: OP

  # Hologram permissions
  chestshop.holograms.see:
    description: See shop holograms
    default: TRUE

  chestshop.holograms.manage:
    description: Manage hologram settings
    default: OP

  # Admin permissions
  chestshop.admin.*:
    description: Grants access to all admin commands
    children:
      - chestshop.admin.removeall
      - chestshop.admin.cleanup
      - chestshop.admin.stats
      - chestshop.admin.reload
      - chestshop.admin.holograms
      - chestshop.admin.reset
      - chestshop.admin.maintenance
      - chestshop.admin.backup
      - chestshop.admin.restore
    default: OP

  chestshop.admin.removeall:
    description: Remove all shops of a player
    default: OP

  chestshop.admin.cleanup:
    description: Clean up invalid shops
    default: OP

  chestshop.admin.stats:
    description: View server statistics
    default: OP

  chestshop.admin.reload:
    description: Reload plugin configuration
    default: OP

  chestshop.admin.holograms:
    description: Manage player holograms
    default: OP

  chestshop.admin.reset:
    description: Reset player statistics
    default: OP

  chestshop.admin.maintenance:
    description: Toggle maintenance mode
    default: OP

  chestshop.admin.backup:
    description: Create and restore backups
    default: OP

  chestshop.admin.restore:
    description: Restore from backups
    default: OP

  # Statistics permissions
  chestshop.stats.others:
    description: View other players' statistics
    default: OP

  chestshop.stats.server:
    description: View server-wide statistics
    default: OP

  # Search permissions
  chestshop.search.unlimited:
    description: Bypass search distance limits
    default: OP

  chestshop.search.all:
    description: Search all shops regardless of world
    default: OP

  # Economy bypass permissions
  chestshop.economy.no-fee:
    description: Bypass transaction fees
    default: OP

  chestshop.economy.no-tax:
    description: Bypass shop taxes
    default: OP

  chestshop.economy.unlimited:
    description: Bypass economy balance requirements
    default: OP

  # Item Trading permissions
  chestshop.trading.*:
    description: Grants access to all Item Trading features
    children:
      - chestshop.trading.use
      - chestshop.trading.create
      - chestshop.trading.convert
      - chestshop.trading.update
      - chestshop.trading.info
      - chestshop.trading.list
      - chestshop.trading.preview
    default: TRUE

  chestshop.trading.use:
    description: Basic permission to use item trading shops
    default: TRUE

  chestshop.trading.create:
    description: Allows creating item trading shops
    default: TRUE

  chestshop.trading.convert:
    description: Allows converting normal shops to trading shops
    default: TRUE

  chestshop.trading.update:
    description: Allows updating trading shop settings
    default: TRUE

  chestshop.trading.info:
    description: Allows viewing trading shop information
    default: TRUE

  chestshop.trading.list:
    description: Allows listing own trading shops
    default: TRUE

  chestshop.trading.list.others:
    description: Allows listing other players' trading shops
    default: OP

  chestshop.trading.preview:
    description: Allows viewing trading previews
    default: TRUE

  # Item Trading bypass permissions
  chestshop.trading.bypass.cooldown:
    description: Bypass trading cooldowns
    default: OP

  chestshop.trading.bypass.distance:
    description: Bypass trading distance limits
    default: OP

  chestshop.trading.bypass.validation:
    description: Bypass item validation for trading
    default: OP

  chestshop.trading.bypass.restrictions:
    description: Bypass all trading restrictions
    default: OP

  chestshop.trading.create.unlimited:
    description: Create unlimited trading shops
    default: OP

  chestshop.trading.create.free:
    description: Create trading shops without cost
    default: OP

  chestshop.trading.create.banned-items:
    description: Create trading shops with banned items
    default: OP

  chestshop.trading.mixed-mode:
    description: Create mixed trading/money shops
    default: OP

  chestshop.trading.cross-world:
    description: Allow cross-world item trading
    default: OP

  chestshop.trading.admin.*:
    description: All trading admin permissions
    children:
      - chestshop.trading.list.others
      - chestshop.trading.bypass.*
      - chestshop.trading.create.unlimited
      - chestshop.trading.create.free
      - chestshop.trading.create.banned-items
      - chestshop.trading.mixed-mode
      - chestshop.trading.cross-world
    default: OP

  # Legacy admin permissions (for backwards compatibility)
  chestshop.admin:
    description: Administrative permissions for ChestShops
    children:
      - chestshop.admin.reload
      - chestshop.admin.removeall
      - chestshop.list.others
      - chestshop.create.unlimited
      - chestshop.create.free
      - chestshop.protection.bypass
    default: OP

  chestshop.reload:
    description: Allows reloading the configuration
    default: OP

  chestshop.remove.others:
    description: Allows removing other players' shops
    default: OP

  chestshop.bypass.limit:
    description: Bypasses the shop limit
    default: OP

  chestshop.bypass.cost:
    description: Bypasses creation costs
    default: OP

  chestshop.bypass.protection:
    description: Bypasses shop protection
    default: OP
